name: Release acceptance

on:
  push:
    tags:
      - 'acceptance/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: /bin/bash .github/workflows/build.sh acceptance
      
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*
